// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkwslmkckhtywydvccpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrd3NsbWtja2h0eXd5ZHZjY3BuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NDg5NzAsImV4cCI6MjA3MzIyNDk3MH0.UiBCrsXlzRuG6Pza05tAkTezFhb56iBv1jI4XE6lxxI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});